#!/bin/bash
set -euo pipefail

: "${RSYNC_REMOTE:?RSYNC_REMOTE must be set (e.g. rsync://mirror.example.org)}"
: "${SYNC_INTERVAL:=21600}"

LOCKFILE="/tmp/sync.lock"
QFM_CONF="/etc/quick-fedora-mirror.conf"
QFM_RUNTIME_CONF="/tmp/qfm-runtime.conf"
QFM_BIN="/opt/quick-fedora-mirror/quick-fedora-mirror"
QFH_BIN="/opt/quick-fedora-mirror/quick-fedora-hardlink"

detect_releases() {
    rsync --list-only "${RSYNC_REMOTE}/fedora-enchilada/linux/releases/" 2>/dev/null \
        | awk '/^d/ {print $NF}' \
        | grep -E '^[0-9]+/?$' \
        | tr -d '/' \
        | sort -n \
        | tail -2
}

generate_runtime_conf() {
    local releases
    releases=$(detect_releases)
    local count
    count=$(echo "$releases" | wc -l)

    if [[ "$count" -lt 2 ]]; then
        echo "WARNING: Found fewer than 2 releases upstream, syncing all available" >&2
    fi

    local version_excludes=""
    for dir in $(rsync --list-only "${RSYNC_REMOTE}/fedora-enchilada/linux/releases/" 2>/dev/null \
        | awk '/^d/ {print $NF}' \
        | grep -E '^[0-9]+/?$' \
        | tr -d '/'); do
        if ! echo "$releases" | grep -qx "$dir"; then
            version_excludes="${version_excludes}|/releases/${dir}/|/updates/${dir}/"
        fi
    done

    # Write the final config
    cp "$QFM_CONF" "$QFM_RUNTIME_CONF"
    cat >> "$QFM_RUNTIME_CONF" <<EOF

# Runtime overrides (generated by sync-entrypoint.sh)
REMOTE=${RSYNC_REMOTE}
FILTEREXP='(/i386|/armhfp|/ppc64/|/ppc64le|/s390x|/source|/SRPMS|/debug/|/releases/test${version_excludes})'
EOF

    if [[ -n "${CHECKIN_SITE:-}" ]]; then
        cat >> "$QFM_RUNTIME_CONF" <<EOF
CHECKIN_SITE=${CHECKIN_SITE}
CHECKIN_PASSWORD=${CHECKIN_PASSWORD:-}
CHECKIN_HOST=${CHECKIN_HOST:-$(hostname 2>/dev/null || echo localhost)}
EOF
    fi

    echo "Runtime config generated. Keeping releases: $(echo "$releases" | tr '\n' ' ')" >&2
}

do_sync() {
    echo "=== Starting sync at $(date -Iseconds) ===" >&2

    generate_runtime_conf

    echo "Running quick-fedora-mirror..." >&2
    flock -n "$LOCKFILE" "$QFM_BIN" -c "$QFM_RUNTIME_CONF" || {
        echo "Sync already running or failed (exit $?), skipping" >&2
        return 1
    }

    echo "Running quick-fedora-hardlink..." >&2
    "$QFH_BIN" -c "$QFM_RUNTIME_CONF" || {
        echo "Hardlink failed (exit $?), continuing" >&2
    }

    touch /data/.sync-complete
    echo "=== Sync complete at $(date -Iseconds) ===" >&2
}

shutdown() {
    echo "Received shutdown signal, cleaning up..." >&2
    kill "$SLEEP_PID" 2>/dev/null || true
    wait "$SLEEP_PID" 2>/dev/null || true
    exit 0
}

trap shutdown SIGTERM SIGINT

# Initial sync
do_sync || true

# Sync loop
while true; do
    sleep "$SYNC_INTERVAL" &
    SLEEP_PID=$!
    wait "$SLEEP_PID" || true
    do_sync || true
done
